BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Users` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Username`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL,
	`PermissionType`	INTEGER NOT NULL
);
INSERT INTO `Users` VALUES (1,'Admin','admin','admin',101);
INSERT INTO `Users` VALUES (2,'Admin2','admin2','admin2',102);
CREATE TABLE IF NOT EXISTS `Quizzes` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT,
	`PreparedBy`	TEXT,
	`IsActive`	INTEGER
);
INSERT INTO `Quizzes` VALUES (1,'Quiz1','Exercise 1','Jen Macaso',1);
CREATE TABLE IF NOT EXISTS `QuizResult` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`QuizId`	INTEGER NOT NULL,
	`StudentName`	TEXT NOT NULL,
	`Result`	TEXT NOT NULL,
	`Answers`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Questions` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`QuestionTypeId`	INTEGER NOT NULL,
	`Answer`	TEXT NOT NULL,
	`QuizId`	INTEGER
);
INSERT INTO `Questions` VALUES (1,'Which animal barks',1,'Dog',1);
INSERT INTO `Questions` VALUES (2,'10 + 1',2,'11',1);
INSERT INTO `Questions` VALUES (3,'Which animal swims',1,'Fish',1);
CREATE TABLE IF NOT EXISTS `QuestionType` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
INSERT INTO `QuestionType` VALUES (1,'Multiple Choice',NULL);
INSERT INTO `QuestionType` VALUES (2,'Fill in the blank',NULL);
CREATE TABLE IF NOT EXISTS `Options` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`QuestionId`	INTEGER NOT NULL
);
INSERT INTO `Options` VALUES (1,'Dog',1);
INSERT INTO `Options` VALUES (2,'Fish',1);
INSERT INTO `Options` VALUES (3,'Cat',1);
INSERT INTO `Options` VALUES (4,'Bird',3);
INSERT INTO `Options` VALUES (5,'Goat',3);
INSERT INTO `Options` VALUES (6,'Fish',3);
COMMIT;
